### PR TITLE
Fix issue 149 by appointing a unique uid to each sink operator.

### LINKED ISSUE #149: [Bug] CDCTools job cannot restart from previous checkpoint/savepoint when multiple tables in sync
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.4.0

### What's Wrong?

CDCTools job cannot restart from previous checkpoint/savepoint when multiple tables in sync.

### What You Expected?

The job should be able to use previous checkpoint/savepoint to restart.

### How to Reproduce?

To reproduce, sync multiple tables, for example:
--including-tables test|test2|test_clone|test_clone2

The reason is that Flink is a stateful application, and it is recommended by official that each stateful operator should have a unique uid.
I fixed this issue by using table name as the uid of its associated sink operators.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cygnusdark**
# Proposed changes

Issue Number: close #149 

## Problem Summary:

Fix issue 149 by appointing a unique uid to each sink operator.

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No
3. Has document been added or modified: No
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

### CODE REVIEW

**Comment by JNSimba** [comment]
Thanks for your contribution, good job
By the way, when adding a new table, need to specify `--allowNonRestoredState`. 
Can this PR solve this problem?

**Comment by cygnusdark** [comment]
Yes. When adding a new table, if the previous sink operators had unique uid, `-allowNonRestoredState` argument is no need any more. 
If `-allowNonRestoredState` used, the exact-once semantics will be broken, so I think this PR gives a better way to support adding new tables.

**Comment by DongLiang-0** [comment]
LGTM

**Review by JNSimba — APPROVED** [review]
LGTM, thank you for your contribution

**Pull request merged**
