### PR TITLE
Repairing packaging with error when packaging 1.17.x

### LINKED ISSUE #229: [Bug] Repairing packaging with error when packaging 1.17.x
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Packaging with error when packaging 1.17.x

 Unable to generate classpath: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
[ERROR] ----------
[ERROR] 1) org.apache.maven.surefire:surefire-junit4:jar:2.22.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit4 -Dversion=2.22.0 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=org.apache.maven.surefire -DartifactId=surefire-junit4 -Dversion=2.22.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]         1) dummy:dummy:jar:1.0
[ERROR]         2) org.apache.maven.surefire:surefire-junit4:jar:2.22.0
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   dummy:dummy:jar:1.0

### What You Expected?

Successfully packaged

### How to Reproduce?

_No response_

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by cjj2010**
Repairing packaging with error when packaging 1.17.x

# Proposed changes

Issue Number: close #229 Repairing packaging with error when packaging 1.17.x

### CODE REVIEW

**Comment by cjj2010** [comment]
Hi，@JNSimba , can you review the issue I fixed? Thank you very much

**Comment by JNSimba** [comment]
What is your compilation command?

**Comment by cjj2010** [comment]
> What is your compilation command?

I checked out from the master branch，cd /home/demo/doris-flink-connector/flink-doris-connector，then execute ./build.sh
image
image

**Comment by JNSimba** [comment]
Thanks for the reply, but I tested it on both mac and linux platforms, and it can be built directly. I guess it may have something to do with your environment? Maybe you can test it in another environment?
image

**Comment by cjj2010** [comment]
> Thanks for the reply, but I tested it on both mac and linux platforms, and it can be built directly. I guess it may have something to do with your environment? Maybe you can test it in another environment? image

Thank you very much for your help. I have found the reason. It is because my local JFog artifact repository cannot download the dependent package. Replacing the Maven repository source can successfully compile. I'll close the issue first

**Pull request closed without merging**
