### PR TITLE
[fix] Fix the bug that the `DorisTypeMapper` datetime type will lose precision when converted to flink type

### LINKED ISSUE #378: [Bug] The `DorisTypeMapper` datetime type will lose precision when converted to flink type
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

The field type of my doris table is datetime at the millisecond level, but when I use flink doris catalog, the writing will only be at the second level.

### What You Expected?

The types should correspond

### How to Reproduce?

_No response_

### Anything Else?

no

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
# Proposed changes

Issue Number: close #378

## Problem Summary:

#378

## Checklist(Required)

1. Does it affect the original behavior: (Yes/No/I Don't know)
2. Has unit tests been added: (Yes/No/No Need)
3. Has document been added or modified: (Yes/No/No Need)
4. Does it need to update dependencies: (Yes/No)
5. Are there any changes that cannot be rolled back: (Yes/No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JNSimba** [comment]
Did you create the table through catalog?

**Comment by huyuanfeng2018** [comment]
> Did you create the table through catalog?

no, it was not created through flink doris catalog

**Comment by JNSimba** [comment]
How was that triggered? In theory, the catalog will reach this point

**Comment by huyuanfeng2018** [comment]
> How was that triggered? In theory, the catalog will reach this point

Then the doris table is created through the doris command and then written through flink
image
As shown in the figure, the stime field is at the millisecond level. I write it through flink.

```
USE CATALOG doris;
insert into doris.db,table xxx
```
The `DorisCatalog#getTable` method will return the mapping of the doris table to the flink table. The precision is not considered when processing the datetime type.

image

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
