### PR TITLE
[fix] extend varchar column length in table auto created by script

### PR DESCRIPTION
**Pull request by zhxiaofan**
# Proposed changes

Issue Number: #159

## Problem Summary:

change varchat length from 3 times origin  length to 4 

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

### CODE REVIEW

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
Thanks for your contribution, but there are some build errors, can they be fixed?

**Comment by zhxiaofan** [comment]
> Thanks for your contribution, but there are some build errors, can they be fixed?

how to fix build error in this PR? The build error is column length assertion error-TestJsonDebeziumSchemaSerializer.testExtractDDLListRename ,this code was submitted after this PR .
should i make a new PR ?

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
