### PR TITLE
[improve] modify type judgement statements

### PR DESCRIPTION
**Pull request by MaoMiMao**
# Proposed changes

 The typeMismatchMessage method creates a string object describing the error every time, but this object is only used when there is a type mismatch. This impacts performance and memory.

Issue Number: NO

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: No
2. Has unit tests been added: No Need
3. Has document been added or modified: No Need
4. Does it need to update dependencies: No
5. Are there any changes that cannot be rolled back: No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JNSimba — APPROVED** [review]
LGTM

**Comment by JNSimba** [comment]
ci failed, PTAL@MaoMiMao

**Comment by MaoMiMao** [comment]
@JNSimba Resolved

**Review by JNSimba — APPROVED** [review]
LGTM

**Pull request merged**
